config/routes.rb
Rails.application.routes.draw do


  # resources :contacts,  only: [:new, :create]

  # resources :users

  root to: 'years#index'
  resources :books
  resources :authors
  resources :years
  resources :awards

end

app/models/author.rb
class Author < ApplicationRecord

  has_and_belongs_to_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_year, presence: true, numericality: true
  validates :birth_place, presence: true

  def self.to_csv
    attributes = %w(first_name last_name birth_year death_year birth_place full_name )
    CSV.generate( headers: true ) do |csv|
      csv << attributes

      all.each do |author|
        csv << author.attributes.values_at(*attributes)
      end
    end
  end

  def self.author_search(search)
    where("full_name ILIKE ?", "%#{search}%")
  end

  def self.book_search(search)
    joins(:books).where("title ILIKE ?", "%#{search}%")
  end

  def self.death_year_search(search)
    where("death_year ILIKE ?", "%#{search}%")
  end

  def self.birth_place_search(search)
    where("birth_place ILIKE ?", "%#{search}%")
  end

  def self.birth_year_search(search)
    where("birth_year ILIKE ?", "%#{search}%")
  end

  def self.award_search(search)
    where(self.total_awards = ?, "%#{search}%")
  end

  def prev
    Author.unscoped.where('last_name < ?', last_name).order('last_name ASC').last
  end

  def next
    Author.unscoped.where('last_name > ?', last_name).order('last_name ASC').first
  end

  def total_awards
    total = 0
    self.books.each do |book|
      book.awards.each do |award|
        total += 1
      end
    end
    return total
  end

  

  # def self.sort_by_total_awards
  #   Author.all.sort_by(&:total_awards)
  # end

end

app/controllers/authors_controller.rb
class AuthorsController < ApplicationController

  helper_method :sort_column, :sort_direction

  def index
    @authors = Author.order("#{sort_column} #{sort_direction}")

    if params[:author_search]
      @authors = @authors.author_search(params[:author_search]).order("created_at DESC")
    else
      @authors = @authors.all.order("created_at DESC")
    end

    respond_to do |format|
      format.html
      format.csv { send_data @authors.to_csv }
    end
  end

  def show
    @author = Author.find(params[:id])
  end

  def new
    @author = Author.new(params[:id])
  end

  def create
    @author = Author.create(author_params)
    @author.full_name = "#{@author.first_name} #{@author.last_name}"
    if @author.save
      redirect_to authors_path
    else
      render :new
    end
  end

  def edit
    @author = Author.find(params[:id])
  end

  def update
    @author = Author.find(params[:id])
    if @author.update(author_params)
      redirect_to authors_path
    else
      render :edit
    end
  end

  def destroy
    @author = Author.find(params[:id]).destroy
    redirect_to years_path
  end

  # def sort_by_awards
  #   @authors = Author.sort_by_total_awards
  #   redirect_to authors_path
  # end

  private

  def sortable_columns
    ["last_name", "birth_year", "death_year", "birth_place"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "last_name"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def author_params
    params.require(:author).permit(:first_name, :last_name, :birth_year, :death_year, :birth_place)
  end
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to "#{title}".html_safe, {column: column, direction: direction}
  end
end

app/views/authors/_form.html.erb
<section class="new-edit-form">

  <%= form_for @author do |f| %>
  <ul>
    <li>
      <%= f.label :first_name %>
      <%= f.text_field :first_name %>
    </li>
    <li>
      <%= f.label :last_name %>
      <%= f.text_field :last_name %>
    </li>
    <li>
      <%= f.label :birth_year %>
      <%= f.text_field :birth_year %>
    </li>
    <li>
      <%= f.label :death_year %>
      <%= f.text_field :death_year %>
    </li>
    <li>
      <%= f.label :birth_place %>
      <%= f.text_field :birth_place %>
    </li>
    <li>
      <%= f.submit "save" %>
    </li>
  </ul>


  <% end %>
  <li>
    <%= button_to "cancel", :back, method: :get %>
  </li>
</section>

app/views/authors/edit.html.erb
<section class="edit-author-page">
  <h2 class="edit-header">Editing <span class="edit-name"><%=@author.full_name%></span></h2>
  <%= render partial: "form" %>
</section>

app/views/authors/index.html.erb
<!-- add sort functionality for authors -->
<%= form_tag(authors_path, method: :get, id: "search-form") do %>
<%= text_field_tag :author_search, params[:author_search], placeholder: "Author" %>
<%= submit_tag "Search", name: nil %>
<% end %>
<%= button_to 'Reset Search', authors_path, method: :get %>
<section class="index-content">
  <h1 class="index-header">All Authors</h1>


  <% if @authors.size == 0 %>
  <p class="none-found">
    No authors found.
  </p>
  <% else %>

  <table class="index-table">
    <tr class="centered">
      <th>
        Awards
      </th>
      <th class="sort-link">
        <%= sort_link "last_name", "Author" %>
      </th>
      <th class="sort-link">
        <%= sort_link "birth_year", "Birth" %>
      </th>
      <th class="sort-link">
        <%= sort_link "death_year", "Death" %>
      </th>
      <th class="sort-link">
        <%= sort_link "birth_place", "Birthplace" %>
      </th>
      <th>
        Books
      </th>
    </tr>
    <% @authors.each do |author| %>
    <tr>
      <td class="author-total-awards">
        <%= author.total_awards %>
      </td>

      <td>
        <%= link_to author.full_name, author_path(author.id) %>
      </td>

      <td class="centered">
        <%= author.birth_year %>
      </td>

      <td class="centered">
        <%= author.death_year %>
      </td>

      <td class="centered">
        <%= author.birth_place %>
      </td>
      <td>

        <table class="books-awards">
          <% author.books.order(:title).each do |book| %>
          <tr>
            <td>
              <%= link_to book.title, book_path(book.id) %>
            </td>
            <td>
              <ul>
                <% book.awards.each do |award| %>
                <li>
                (<%= award.award_type %> <%= award.year.year %>)
              </li>
              <% end %>
            </ul>
          </td>
        </tr>
        <% end %>
      </table>
    </td>
  </tr>
  <% end %>

</table>
<% end %>

</section>

app/views/authors/new.html.erb
<section class="new-author-page">
  <h2 class="new-header">New Author</h2>
  <%= render partial: "form" %>
</section>

app/views/authors/search.html.erb
<h1>Author Search</h1>
<!-- add sort functionality for authors -->

<ul>
  <% @authors.each do |author| %>
  <% author_name = "#{author.first_name} #{author.last_name}" %>
  <% author_years = "#{author.birth_year}-#{author.death_year}" %>
    <li>
      <%= link_to author_name, author_path(author.id) %> (<%=author_years%>), born in <%= author.birth_place %>
    </li>
  <% end %>
  <% if @authors.size == 0 %>
    <p>
      No authors found.
    </p>
  <% end %>
</ul>

app/views/authors/show.html.erb
<article class="show-content">

  <ul class="next-prev">
    <li class="left">
      <%= link_to "Previous Author", @author.prev %>
    </li>
    <li class="right">
      <%= link_to "Next Author", @author.next %>
    </li>
  </ul>

  <h1 class="show-title"><%= @author.full_name %> (<%=@author.birth_year%>-<%=@author.death_year%>)</h1>

  <section class="show-data">

    <p class="author-origin">
      <%= @author.full_name %> is originally from <%= @author.birth_place %>.
    </p>

    <h2 class="books-list-header">Books</h2>

    <section class="author-books-list">
      <% if @author.books.size == 0 %>
      <p class="none-found">
        No books found.
      </p>
      <% else %>
      <table class="author-books-table">
        <tr>
          <th>
            Title
          </th>
          <th>
            Award
          </th>

        </tr>
        <% books = @author.books.order(:title) %>
        <% books.each do |book| %>
        <tr>
          <td>
            <%= link_to book.title, book_path(book.id) %>
          </td>

          <td class="book-award">
            <ul>

              <% book.awards.each do |award| %>
              <li>
                <%= award.award_type %>
                <%= award.year.year %>
              </li>
              <% end %>
            </ul>
          </td>

        </tr>
        <% end %>
      </table>
      <% end %>

    </section>

  </section>

  <section class="show-links-bottom">

    <ul>

      <li>
        <%= link_to "edit author", edit_author_path(@author.id) %>
      </li>
      <li>
        <%= link_to "back", :back %>
      </li>
      <li>
        <%= link_to "delete author", author_path(@author.id), method: :delete, data: { confirm: "Really delete this author?" }  %>
      </li>

    </ul>

  </section>

</article>