config/routes.rb
Rails.application.routes.draw do


  # resources :contacts,  only: [:new, :create]

  # resources :users

  root to: 'years#index'
  resources :books
  resources :authors
  resources :years
  resources :awards

end

app/models/book.rb
class Book < ApplicationRecord

  # AWARDS = {"Nebula" => "Nebula", "Hugo" => "Hugo", "Nebula & Hugo" => "Nebula & Hugo"}
  has_and_belongs_to_many :authors
  has_many :awards
  # belongs_to :year

  validates :title, presence: true
  # validates :author_id, presence: true
  validates :publisher, presence: true
  validates :description, presence: true
  # validates :year_id, presence: true

  def self.to_csv
    attributes = %w(title cover publisher description author_ids)
    CSV.generate( headers: true ) do |csv|
      csv << attributes

      all.each do |book|
        csv << book.attributes.values_at(*attributes)
      end
    end
  end

  def self.search_description(search)
    where("description ILIKE ?", "%#{search}%")
  end

  def self.main_search(search)
    where("title ILIKE ?", "%#{search}%")
  end


  def prev
    Book.unscoped.where('title < ?', title).order('title ASC').last
  end

  def next
    Book.unscoped.where('title > ?', title).order('title ASC').first
  end


end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  helper_method :sort_column, :sort_direction

  def index
    @books = Book.order("#{sort_column} #{sort_direction}")
    respond_to do |format|
      format.html
      format.csv { send_data @books.to_csv }
    end

    if params[:main_search]
      @books = @books.main_search(params[:main_search]).order("created_at DESC")
    elsif params[:search_description]
      @books = @books.search_description(params[:search_description]).order("created_at DESC")
    else
      @books = @books.all.order("created_at DESC")
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new(params[:id])
  end

  def create
    @book = Book.create(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    # author = Author.find_by_id(params[:book][:author_id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.awards.each do |award|
      award.destroy
    end
    @book.destroy
    redirect_to years_path
  end

  private

  def sortable_columns
    ["title", "author"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def book_params
    params.require(:book).permit(:title, :cover, :publisher, :description, author_ids: [])
  end
end

app/helpers/books_helper.rb
module BooksHelper

  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to "#{title}".html_safe, {column: column, direction: direction}
  end

end

app/views/books/_add_author.html.erb
<section class="add-author-form">

  <%= form_for @book do |f| %>
    <ul>
      <li>
        <%= f.label :author_id %>
        <%= f.collection_select(:author_id, Author.all.order(:last_name), :id, :full_name) %>
      </li>
      <li>
        <%= f.submit "add author" %>
      </li>
    </ul>


  <% end %>
  <li>
    <%= button_to "cancel", :back, method: :get %>
  </li>
</section>

app/views/books/_form.html.erb
<section class="new-edit-form">

  <%= form_for @book do |f| %>
    <ul>
      <li>
        <%= f.label :title %>
        <%= f.text_field :title %>
      </li>
      <li>
        <%= f.label :cover %>
        <%= f.text_field :cover %>
      </li>
      <li>
        <%= f.label :publisher %>
        <%= f.text_field :publisher %>
      </li>
      <li>
        <%= f.label :description %>
        <%= f.text_area :description %>
      </li>
      <li>
        <%= f.label "Author(s)" %>
        <%= f.collection_select :author_ids, Author.order(:last_name), :id, :full_name, {}, {multiple: true} %>
      </li>

      <li>
        <%= f.submit "save" %>
      </li>
    </ul>


  <% end %>
  <li>
    <%= button_to "cancel", :back, method: :get %>
  </li>
</section>

app/views/books/addauthor.html.erb
<section class="add-author-page">
  <h2 class="new-header">Add Author to Book</h2>
  <%= render partial: "add_author" %>
</section>

app/views/books/edit.html.erb
<section class="edit-book-page">
  <h2 class="edit-header">Editing <span class="edit-name"><%=@book.title%></span></h2>
  <%= render partial: "form" %>
</section>

app/views/books/index.html.erb
<ul class="search">
<li>
<%= form_tag(books_path, method: :get , id: "search-form") do %>
<%= text_field_tag :search_description, params[:search_description], placeholder: "Description" %>
<%= submit_tag "Search", :name => nil %>
<% end %>
</li>
<li>
<%= form_tag(books_path, method: :get , id: "search-form") do %>
<%= text_field_tag :main_search, params[:main_search], placeholder: "Title" %>
<%= submit_tag "Search", :name => nil %>
<% end %>
</li>
<li>
<%= button_to 'Reset', books_path, method: :get %>
</li>
</ul>

<section class="index-content">
  <h1 class="index-header">All Books</h1>

  <% if @books.empty? %>
  <p class="none-found">
    No books found.
  </p>
  <% else %>

  <table class="index-table">
    <tr class="centered">
      <th class="sort-link">
        <%= sort_link "title" %>
      </th>
      <th>
        Author
      </th>
      <th>
        Award
      </th>
    </tr>
    <% @books.each do |book| %>
    <tr>
      <td >
        <%= link_to book.title, book_path(book.id) %>
      </td>
      <td class="centered">
        <ul>
          <% book.authors.each do |author| %>
          <li>
            <%= link_to author.full_name, author_path(author.id) %>
          </li>
          <% end %>
        </ul>
      </td>
      <td class="centered">
        <% if book.awards.empty? %>
          <p>
            no awards yet
          </p>
          <% else %>
          <ul>

        <% book.awards.each do |award| %>
        <li>
          <%= award.award_type %> <%= award.year.year %>
        </li>
        <% end %>
      </ul>

        <% end %>
      </td>
    </tr>
    <% end %>


  </table>
  <% end %>
</section>

app/views/books/new.html.erb
<section class="new-book-page">
  <h2 class="new-header">New Book</h2>
  <%= render partial: "form" %>
</section>

app/views/books/show.html.erb
<article class="show-content">

    <ul class="next-prev">
      <li class="left">
        <%= link_to "Previous Book", @book.prev %>
      </li>
      <li class="right">
        <%= link_to "Next Book", @book.next %>
      </li>
    </ul>
  <article class="left-right">

    <section class="show-left">
      <h1 class="show-title"><%=@book.title%></h1>
      <ul class="show-details">
        <li class="book-detail-author">
          <% @book.authors.each do |author| %>
          <%= link_to author.full_name, author_path(author.id) %>
          <% end %>
        </li>
        <li class="description">
          <%= @book.description %>*
        </li>
        <li class="book-detail-publisher">
          Publisher: <%= @book.publisher %>
        </li>

        <li class="description-attribution">
          *Most information found at <%= link_to "Wikipedia", "http://www.wikipedia.com" %>, <%= link_to "Goodreads", "http://www.goodreads.com" %>, or <%= link_to "ISFDB", "http://www.isfdb.org" %>. Please see these fabulous sites for more book information and reviews, etc.
        </li>
      </ul>
    </section>
    <section class="show-right">
      <%= image_tag @book.cover, class: "book-cover" %>
      <p class="book-award-text">
        <% @book.awards.each do |award| %>
        <%= award.award_type %>
        <% end %>
      </p>
    </section>
  </article>

  <ul class="show-links-bottom">
    <%# image_tag("award_pic", size: "50x50") %>
    <li>
      <%= link_to "edit book", edit_book_path(@book.id) %>
    </li>
    <li>
      <%= link_to "back", :back %>
    </li>
    <li>
      <%= link_to "delete book", book_path(@book.id), method: :delete, data: { confirm: "Really delete this book?" }  %>
    </li>

  </ul>

</article>