config/routes.rb
Rails.application.routes.draw do


  # resources :contacts,  only: [:new, :create]

  # resources :users

  root to: 'years#index'
  resources :books
  resources :authors
  resources :years
  resources :awards

end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
  require 'csv'
end

app/models/author.rb
class Author < ApplicationRecord

  has_and_belongs_to_many :books

  validates :first_name, presence: true
  validates :last_name, presence: true
  validates :birth_year, presence: true, numericality: true
  validates :birth_place, presence: true

  def self.to_csv
    attributes = %w(first_name last_name birth_year death_year birth_place full_name )
    CSV.generate( headers: true ) do |csv|
      csv << attributes

      all.each do |author|
        csv << author.attributes.values_at(*attributes)
      end
    end
  end

  def self.author_search(search)
    where("full_name ILIKE ?", "%#{search}%")
  end

  def self.book_search(search)
    joins(:books).where("title ILIKE ?", "%#{search}%")
  end

  def self.death_year_search(search)
    where("death_year ILIKE ?", "%#{search}%")
  end

  def self.birth_place_search(search)
    where("birth_place ILIKE ?", "%#{search}%")
  end

  def self.birth_year_search(search)
    where("birth_year ILIKE ?", "%#{search}%")
  end

  def self.award_search(search)
    where(self.total_awards = ?, "%#{search}%")
  end

  def prev
    Author.unscoped.where('last_name < ?', last_name).order('last_name ASC').last
  end

  def next
    Author.unscoped.where('last_name > ?', last_name).order('last_name ASC').first
  end

  def total_awards
    total = 0
    self.books.each do |book|
      book.awards.each do |award|
        total += 1
      end
    end
    return total
  end

  

  # def self.sort_by_total_awards
  #   Author.all.sort_by(&:total_awards)
  # end

end

app/models/authors_book.rb
class AuthorsBook < ApplicationRecord
  belongs_to :book
  belongs_to :authors
end

app/models/award.rb
class Award < ApplicationRecord
  belongs_to :year
  belongs_to :book

  default_scope { joins(:year).order('year ASC') }

  scope :award_book, -> { joins("left join awards on book_id = books.id").order("books.title") }

  validates :award_type, presence: true
  AWARDS = {"Nebula" => "Nebula", "Hugo" => "Hugo", "Aurora" => "Aurora"}

  def self.to_csv
    attributes = %w(award_type year_id book_id)
    CSV.generate( headers: true ) do |csv|
      csv << attributes

      all.each do |award|
        csv << award.attributes.values_at(*attributes)
      end
    end
  end


end

app/models/book.rb
class Book < ApplicationRecord

  # AWARDS = {"Nebula" => "Nebula", "Hugo" => "Hugo", "Nebula & Hugo" => "Nebula & Hugo"}
  has_and_belongs_to_many :authors
  has_many :awards
  # belongs_to :year

  validates :title, presence: true
  # validates :author_id, presence: true
  validates :publisher, presence: true
  validates :description, presence: true
  # validates :year_id, presence: true

  def self.to_csv
    attributes = %w(title cover publisher description author_ids)
    CSV.generate( headers: true ) do |csv|
      csv << attributes

      all.each do |book|
        csv << book.attributes.values_at(*attributes)
      end
    end
  end

  def self.search_description(search)
    where("description ILIKE ?", "%#{search}%")
  end

  def self.main_search(search)
    where("title ILIKE ?", "%#{search}%")
  end


  def prev
    Book.unscoped.where('title < ?', title).order('title ASC').last
  end

  def next
    Book.unscoped.where('title > ?', title).order('title ASC').first
  end


end

app/models/contact.rb
class Contact < MailForm::Base
  attribute :name,      :validate => true
  attribute :email,     :validate => /\A([\w\.%\+\-]+)@([\w\-]+\.)+([\w]{2,})\z/i
  attribute :message
  attribute :nickname,  :captcha  => true

  # Declare the e-mail headers. It accepts anything the mail method
  # in ActionMailer accepts.
  def headers
    {
      :subject => "Your Subject Here",
      :to => "aurora.lemieux@gmail.com",
      :from => %("#{name}" <#{email}>)
    }
  end
end

app/models/year.rb
class Year < ApplicationRecord
  has_many :awards

  validates :year, presence: true

  def self.to_csv
    attributes = %w(year)
    CSV.generate( headers: true ) do |csv|
      csv << attributes

      all.each do |user|
        csv << user.attributes.values_at(*attributes)
      end
    end
  end

  def self.search(search)
    where("year ILIKE ?", "%#{search}%")
  end

end

app/controllers/books_controller.rb
class BooksController < ApplicationController

  helper_method :sort_column, :sort_direction

  def index
    @books = Book.order("#{sort_column} #{sort_direction}")
    respond_to do |format|
      format.html
      format.csv { send_data @books.to_csv }
    end

    if params[:main_search]
      @books = @books.main_search(params[:main_search]).order("created_at DESC")
    elsif params[:search_description]
      @books = @books.search_description(params[:search_description]).order("created_at DESC")
    else
      @books = @books.all.order("created_at DESC")
    end
  end

  def show
    @book = Book.find(params[:id])
  end

  def new
    @book = Book.new(params[:id])
  end

  def create
    @book = Book.create(book_params)
    if @book.save
      redirect_to books_path
    else
      render :new
    end
  end

  def edit
    @book = Book.find(params[:id])
  end

  def update
    @book = Book.find(params[:id])
    # author = Author.find_by_id(params[:book][:author_id])
    if @book.update(book_params)
      redirect_to books_path
    else
      render :edit
    end
  end

  def destroy
    @book = Book.find(params[:id])
    @book.awards.each do |award|
      award.destroy
    end
    @book.destroy
    redirect_to years_path
  end

  private

  def sortable_columns
    ["title", "author"]
  end

  def sort_column
    sortable_columns.include?(params[:column]) ? params[:column] : "title"
  end

  def sort_direction
    %w[asc desc].include?(params[:direction]) ? params[:direction] : "asc"
  end

  def book_params
    params.require(:book).permit(:title, :cover, :publisher, :description, author_ids: [])
  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  def new
  end

  def create
  end
end

app/controllers/years_controller.rb
class YearsController < ApplicationController
  def index
    @years = Year.all.order(:year)

    respond_to do |format|
      format.html
      format.csv { send_data @years.to_csv }
    end

    if params[:search]
      @years = @years.search(params[:search]).order("created_at DESC")
    else
      @years = @years.all.order("created_at DESC")
    end

  end

  def show
    @year = Year.find(params[:id])
  end

  def new
    @year = Year.new(params[:id])
  end

  def create
    @year = Year.create(year_params)
    if @year.save
      redirect_to years_path
    else
      render :new
    end
  end

  def edit
    @year = Year.find(params[:id])
  end

  def update
    @year = Year.find(params[:id])
    if @year.update(year_params)
      redirect_to years_path
    else
      render :edit
    end
  end

  def destroy
    @year = Year.find(params[:id]).destroy
    redirect_to years_path
  end

  private

  def year_params
      params.require(:year).permit(:year)
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/authors_helper.rb
module AuthorsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to "#{title}".html_safe, {column: column, direction: direction}
  end
end

app/helpers/awards_helper.rb
module AwardsHelper
  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to "#{title}".html_safe, {column: column, direction: direction}
  end
end

app/helpers/books_helper.rb
module BooksHelper

  def sort_link(column, title = nil)
    title ||= column.titleize
    direction = column == sort_column && sort_direction == "asc" ? "desc" : "asc"
    link_to "#{title}".html_safe, {column: column, direction: direction}
  end

end

app/helpers/contacts_helper.rb
module ContactsHelper
end

app/helpers/hugos_helper.rb
module HugosHelper
end

app/helpers/nebulas_helper.rb
module NebulasHelper
end

app/helpers/sessions_helper.rb
module SessionsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/years_helper.rb
module YearsHelper
end

app/views/layouts/_form.html.erb
<%= form_for @book do |f| %>
  <ul>
    <li>
      <%= f.label :title %>
      <%= f.text_field :title %>
    </li>
    <li>
      <%= f.label :cover %>
      <%= f.text_field :cover %>
    </li>
    <li>
      <%= f.label :publisher %>
      <%= f.text_field :publisher %>
    </li>
    <li>
      <%= f.label :description %>
      <%= f.text_area :description %>
    </li>
    <li>
      <%= f.label :award %>
      <%= select(:book, :award, Book::AWARDS.keys, {include_blank: true}, required:true ) %>
    </li>
    <li>
      <%= f.label :author_id %>
      <%= f.collection_select(:author_id, Author.all.order(:last_name), :id, :full_name) %>
    </li>
    <li>
      <%= f.label :year_id %>
      <%= f.collection_select(:year_id, Year.all.order(:year), :id, :year) %>
    </li>
    <li>
      <%= f.submit "save" %>
    </li>
    <li>
      <%= link_to "cancel", :back %>
    </li>
  </ul>


<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Award-winning SF Novels</title>
  <%= csrf_meta_tags %>

  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
</head>

<body>
  <header>
    <section class="top-nav">
      <h1 class="main-app-header"><%= link_to "AWARD-WINNING SPEC FIC NOVELS", root_path %></h1>
      <ul class="top-bar-nav">
        <li>
          <%= link_to "new book", new_book_path %>
        </li>
        <li>
          <%= link_to "new author", new_author_path %>
        </li>
        <li>
          <%= link_to "new year", new_year_path %>
        </li>
        <li>
          <%= link_to "new award", new_award_path %>
        </li>
        <li>
          <%= link_to "books", books_path %>
        </li>
        <li>
          <%= link_to "authors", authors_path %>
        </li>
        <li>
          <%= link_to "years", root_path %>
        </li>
        <li>
          <%= link_to "awards", awards_path %>
        </li>
      </ul>
    </section>
  </header>


  <section class="content">
    <section class="flash">
      <% flash.each do |name, message| %>
      <div class="<%= name %>"><%= message %></div>
      <% end %>
    </section>
    <%= yield %>
  </section>
  <footer>
    <section class="bottom-nav">
      <ul>
        <li>
          &copy; 2017
        </li>
        <li>
          <%= link_to "aurora lemieux anderson", "http://www.github.com/auroralemieux" %>
        </li>
        <li>
          <%# link_to "contact me", new_contact_path %>
        </li>
      </ul>
    </section>
  </footer>


</body>

<div>
  <% flash.each do |key, value| %>
  <div>
    <a href="#" data-dismiss="alert">×</a>
    <%= value %>
  </div>
  <% end %>
</div>
</html>

app/views/layouts/contact.html.erb
<section class="contact-page">
  <h2 class="contact-header">Contact me!</h2>
  <p>
    Find a mistake in a book or author entry? Or just have a question or request? Drop me a line!
  </p>
  <%= render partial: "form" %>
</section>